### PR TITLE
Update test file

### PR DESCRIPTION
**Pull request by jinhyukchang**
Update test file

### CODE REVIEW

**Comment by convexquad** [comment]
@jinhyukchang Can you squash your commits and bump the version of gradle.properties?

**Comment by jinhyukchang** [comment]
@convexquad Just squashed the commit. 
There's one new merge commit which I used to merge from master branch and resolved conflict. I am not sure if there's easy way to squash merge commit other than doing it from new branch. Let me know if you want to squash this one as well.

**Comment by convexquad** [comment]
Yes - the merge commit contains the full history since the merge. This will make it impossible to determine from which commit the changes in the merge commit actually originated from. Can you reset back to whatever version you were at, git stash your changes, then git pull --rebase origin master, and then un-stash your changes and fix any conflicts? You can git push --force over your own GitHub as it is ok to re-write your own changes.

**Comment by jinhyukchang** [comment]
Thanks for tip and I was able to squash into one.

**Comment by convexquad** [comment]
+1

**Pull request merged**
