### PR TITLE
Hadoop validator

### PR DESCRIPTION
**Pull request by nntnag17**
This resolves the conflict in #70

### CODE REVIEW

**Comment by convexquad** [comment]
@nntnag17 Can you squash these commits? If you do so, I'll commit as soon as the Travis CI goes green

**Comment by nntnag17** [comment]
Hi @convexquad ,

There is only a single commit from the PR. The other commit is the merge commit which was created on merging PR #70 to this branch.  Also the two commits are not consecutive so cannot be squashed.

**Comment by convexquad** [comment]
@nntnag17 Ok, you are +1 to merge this PR at your convenience

**Comment by nntnag17** [comment]
Thanks @convexquad, I'm merging it.

**Pull request merged**
