### PR TITLE
Add KubernetesJob job type

### PR DESCRIPTION
**Pull request by UWFrankGu**

### CODE REVIEW

**Comment by li-ygerchikov** [comment]
No expert here but LGTM.

**Comment by oliverhu** [comment]
lgtm.. i think my commit access was removed recently 🤔

**Comment by UWFrankGu** [comment]
> Can you please add a unit test or integration test?

Hi @djaiswal83 I added both positive and missing fields integration tests. I basically followed previously submitted PRs that add new plugins. Is there any specific integration test I'm missing?

**Comment by djaiswal83** [comment]
> > Can you please add a unit test or integration test?
> 
> Hi @djaiswal83 I added both positive and missing fields integration tests. I basically followed previously submitted PRs that add new plugins. Is there any specific integration test I'm missing?

I see. Thanks for clarification. I missed the test.
LGTM.
Let me know if you do not have permission to merge.

**Comment by UWFrankGu** [comment]
> > > Can you please add a unit test or integration test?
> > 
> > 
> > Hi @djaiswal83 I added both positive and missing fields integration tests. I basically followed previously submitted PRs that add new plugins. Is there any specific integration test I'm missing?
> 
> I see. Thanks for clarification. I missed the test.
> LGTM.
> Let me know if you do not have permission to merge.

@djaiswal83 I do not have the permission to merge. Please go ahead and merge thanks!

**Pull request merged**
